(function(){
      var G=1435,H=1250,rows=[];
      function num(v){if(typeof v==='number')return v;return Number(String(v==null?'':v).trim().replace(/\s/g,'').replace(',','.'))}
      function fmt(v,d){return new Intl.NumberFormat('fr-FR',{minimumFractionDigits:d,maximumFractionDigits:d}).format(v)}
      function calc(p,fc,d,h){h=Number.isFinite(h)&&h>0?h:H;if(!Number.isFinite(fc)||!Number.isFinite(d)||Math.abs(d)>=G)return{p:p,ok:false,msg:'Valeur incorrecte'};var r=Math.asin(d/G),a=r*180/Math.PI,c=h*Math.tan(r);return{p:p||'—',fc:fc,d:d,h:h,a:a,c:c,out:fc+c,ok:true}}
      function update(){var r=calc('',num(fc.value),num(devers.value),num(hauteur.value));if(!r.ok)return;resultat.textContent=fmt(r.out,1);arrondi.textContent=Math.round(r.out)+' mm';angle.textContent=fmt(r.a,3)+'°';correction.textContent=(r.c>=0?'+':'')+fmt(r.c,1)+' mm';document.getElementById('height-label').textContent=fmt(r.h/1000,2)+' m'}
      ['fc','devers','hauteur'].forEach(function(id){document.getElementById(id).addEventListener('input',update)});update();
      var file=document.getElementById('file');document.getElementById('choose').onclick=function(){file.click()};
      function show(msg,error){notice.hidden=false;notice.className='notice'+(error?' error':'');notice.textContent=msg}
      file.onchange=function(){var f=file.files[0];if(!f)return;if(!window.XLSX){show('La bibliothèque Excel ne s’est pas chargée. Vérifiez la connexion internet.',true);return}var reader=new FileReader();reader.onload=function(e){try{var wb=XLSX.read(e.target.result,{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],data=XLSX.utils.sheet_to_json(ws,{header:1,defval:''});rows=data.slice(1).filter(function(r){return r.some(function(v){return String(v).trim()!==''})}).map(function(r,i){return calc(String(r[3]||i+1),num(r[1]),num(r[0]),String(r[2]).trim()===''?H:num(r[2]))});render();show(rows.length+' poteau(x) importé(s).',false)}catch(err){show('Impossible de lire ce fichier Excel.',true)}};reader.readAsArrayBuffer(f);file.value=''};
      function render(){tbody.innerHTML='';var valid=0;rows.forEach(function(r){var tr=document.createElement('tr');if(r.ok){valid++;tr.innerHTML='<td><strong>'+esc(r.p)+'</strong></td><td>'+fmt(r.fc,1)+' mm</td><td>'+fmt(r.d,1)+' mm</td><td>'+fmt(r.h,0)+' mm</td><td>'+fmt(r.a,3)+'°</td><td>'+(r.c>=0?'+':'')+fmt(r.c,1)+' mm</td><td><strong>'+fmt(r.out,1)+' mm</strong><small>arrondi '+Math.round(r.out)+' mm</small></td>'}else tr.innerHTML='<td>'+esc(r.p)+'</td><td colspan="6">'+r.msg+'</td>';tbody.appendChild(tr)});count.textContent=rows.length+' poteau(x)';summary.textContent=valid+' calculé(s) · '+(rows.length-valid)+' à vérifier';results.hidden=false}
      function esc(s){return String(s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
      function template(){if(!window.XLSX){show('La bibliothèque Excel ne s’est pas chargée.',true);return}var ws=XLSX.utils.aoa_to_sheet([['Dévers de la voie (mm)','Désaxement FC (mm)','Hauteur FC-porteur (mm)','Numéro de poteau'],[45,-200,1250,'186/27P'],[45,-240,1100,'186/29P']]),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Poteaux');XLSX.writeFile(wb,'modele_devers_porteur.xlsx')}
      document.getElementById('template').onclick=template;
      document.getElementById('excel').onclick=function(){if(!window.XLSX)return;var data=rows.filter(function(r){return r.ok}).map(function(r){return{'Numéro de poteau':r.p,'Désaxement FC (mm)':r.fc,'Dévers de la voie (mm)':r.d,'Hauteur FC-porteur (mm)':r.h,'Angle (°)':+r.a.toFixed(4),'Correction (mm)':+r.c.toFixed(1),'Désaxement porteur (mm)':+r.out.toFixed(1)}}),ws=XLSX.utils.json_to_sheet(data),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Résultats');XLSX.writeFile(wb,'resultats_devers_porteur.xlsx')};
      document.getElementById('csv').onclick=function(){var lines=[['Numéro de poteau','Désaxement FC (mm)','Dévers voie (mm)','Hauteur FC-porteur (mm)','Angle (°)','Correction (mm)','Désaxement porteur (mm)']];rows.filter(function(r){return r.ok}).forEach(function(r){lines.push([r.p,r.fc,r.d,r.h,r.a.toFixed(4),r.c.toFixed(1),r.out.toFixed(1)])});var csv='\ufeff'+lines.map(function(line){return line.map(function(v){return'"'+String(v).replace(/"/g,'""')+'"'}).join(';')}).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='resultats_devers_porteur.csv';a.click()};
    })();
